### ISSUE TITLE
Message encoding on internal auth login screen

### ISSUE THREAD

**Issue by anttileppa** [otavanopisto/pyramus#169] opened 2015-04-24 06:02 UTC
Internal login screen says:
"Virheellinen k�ytt�j�tunnus tai salasana. Ole hyv�ja yrit�uudelleen." when trying to login with invalid credentials

**Comment by anttiviljakainen** [comment] 2016-08-02 07:16
Duplicate of #85

**Closed by anttiviljakainen** 2016-08-02 07:16 UTC
Labels: duplicate
