### ISSUE TITLE
Add comment to contact log's entry

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/pyramus#486] opened 2017-04-10 07:10 UTC
When using Chrome while trying to add comment to contact log's entry the comment editor can't accept focus and therefore renders it impossible to add said comment.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1631

#### SH
Petra Roininen

**Comment by anttiviljakainen** [comment] 2017-05-09 05:40
Duplicate of #283

**Closed** 2017-05-12 10:31 UTC
Labels: bug, groom, helpdesk
